package com.jdy.ddj.entity;

public class DdjArea {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_area.areaid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String areaid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_area.areaname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String areaname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_area.parentid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String parentid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_area.areaid
	 * @return  the value of ddj_area.areaid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getAreaid() {
		return areaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_area.areaid
	 * @param areaid  the value for ddj_area.areaid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_area.areaname
	 * @return  the value of ddj_area.areaname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getAreaname() {
		return areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_area.areaname
	 * @param areaname  the value for ddj_area.areaname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setAreaname(String areaname) {
		this.areaname = areaname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_area.parentid
	 * @return  the value of ddj_area.parentid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_area.parentid
	 * @param parentid  the value for ddj_area.parentid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setParentid(String parentid) {
		this.parentid = parentid;
	}
}