package com.jdy.ddj.entity;

import java.util.Date;

public class DdjBjd {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.ywid
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private Long ywid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.productname
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private String productname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.cpcz
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private String cpcz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.dzlx
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private String dzlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.price
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.khbh
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private Long khbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.cjbh
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private Long cjbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.status
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_bjd.bjtime
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	private Date bjtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.ywid
	 * @return  the value of ddj_bjd.ywid
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public Long getYwid() {
		return ywid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.ywid
	 * @param ywid  the value for ddj_bjd.ywid
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setYwid(Long ywid) {
		this.ywid = ywid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.productname
	 * @return  the value of ddj_bjd.productname
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public String getProductname() {
		return productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.productname
	 * @param productname  the value for ddj_bjd.productname
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setProductname(String productname) {
		this.productname = productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.cpcz
	 * @return  the value of ddj_bjd.cpcz
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public String getCpcz() {
		return cpcz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.cpcz
	 * @param cpcz  the value for ddj_bjd.cpcz
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setCpcz(String cpcz) {
		this.cpcz = cpcz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.dzlx
	 * @return  the value of ddj_bjd.dzlx
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public String getDzlx() {
		return dzlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.dzlx
	 * @param dzlx  the value for ddj_bjd.dzlx
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setDzlx(String dzlx) {
		this.dzlx = dzlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.price
	 * @return  the value of ddj_bjd.price
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.price
	 * @param price  the value for ddj_bjd.price
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.khbh
	 * @return  the value of ddj_bjd.khbh
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public Long getKhbh() {
		return khbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.khbh
	 * @param khbh  the value for ddj_bjd.khbh
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setKhbh(Long khbh) {
		this.khbh = khbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.cjbh
	 * @return  the value of ddj_bjd.cjbh
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public Long getCjbh() {
		return cjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.cjbh
	 * @param cjbh  the value for ddj_bjd.cjbh
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setCjbh(Long cjbh) {
		this.cjbh = cjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.status
	 * @return  the value of ddj_bjd.status
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.status
	 * @param status  the value for ddj_bjd.status
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_bjd.bjtime
	 * @return  the value of ddj_bjd.bjtime
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public Date getBjtime() {
		return bjtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_bjd.bjtime
	 * @param bjtime  the value for ddj_bjd.bjtime
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	public void setBjtime(Date bjtime) {
		this.bjtime = bjtime;
	}


}