package com.jdy.ddj.entity;

public class DdjCompany {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.companyid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long companyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.companyname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String companyname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.intro
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String intro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.logo
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String logo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.address
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.phone
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.jyfw
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String jyfw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.yyzhpic
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String yyzhpic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.pfen
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Integer pfen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.areaid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String areaid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_company.sortid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long sortid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.companyid
	 * @return  the value of ddj_company.companyid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getCompanyid() {
		return companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.companyid
	 * @param companyid  the value for ddj_company.companyid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setCompanyid(Long companyid) {
		this.companyid = companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.companyname
	 * @return  the value of ddj_company.companyname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getCompanyname() {
		return companyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.companyname
	 * @param companyname  the value for ddj_company.companyname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.intro
	 * @return  the value of ddj_company.intro
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.intro
	 * @param intro  the value for ddj_company.intro
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setIntro(String intro) {
		this.intro = intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.logo
	 * @return  the value of ddj_company.logo
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getLogo() {
		return logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.logo
	 * @param logo  the value for ddj_company.logo
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setLogo(String logo) {
		this.logo = logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.address
	 * @return  the value of ddj_company.address
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.address
	 * @param address  the value for ddj_company.address
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.phone
	 * @return  the value of ddj_company.phone
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.phone
	 * @param phone  the value for ddj_company.phone
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.jyfw
	 * @return  the value of ddj_company.jyfw
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getJyfw() {
		return jyfw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.jyfw
	 * @param jyfw  the value for ddj_company.jyfw
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setJyfw(String jyfw) {
		this.jyfw = jyfw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.yyzhpic
	 * @return  the value of ddj_company.yyzhpic
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getYyzhpic() {
		return yyzhpic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.yyzhpic
	 * @param yyzhpic  the value for ddj_company.yyzhpic
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setYyzhpic(String yyzhpic) {
		this.yyzhpic = yyzhpic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.pfen
	 * @return  the value of ddj_company.pfen
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Integer getPfen() {
		return pfen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.pfen
	 * @param pfen  the value for ddj_company.pfen
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setPfen(Integer pfen) {
		this.pfen = pfen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.areaid
	 * @return  the value of ddj_company.areaid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getAreaid() {
		return areaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.areaid
	 * @param areaid  the value for ddj_company.areaid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_company.sortid
	 * @return  the value of ddj_company.sortid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getSortid() {
		return sortid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_company.sortid
	 * @param sortid  the value for ddj_company.sortid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setSortid(Long sortid) {
		this.sortid = sortid;
	}
}