package com.jdy.ddj.entity;

public class DdjCkb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.ckid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private Long ckid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.userid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.ckname
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private String ckname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.ckaddress
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private String ckaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.cklxrid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private Long cklxrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.cktype
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private Integer cktype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.ckqhdz
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private String ckqhdz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.ckshdz
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private String ckshdz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.status
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	private Short status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.ckid
	 * @return  the value of ddj_ckb.ckid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public Long getCkid() {
		return ckid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.ckid
	 * @param ckid  the value for ddj_ckb.ckid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setCkid(Long ckid) {
		this.ckid = ckid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.userid
	 * @return  the value of ddj_ckb.userid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.userid
	 * @param userid  the value for ddj_ckb.userid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.ckname
	 * @return  the value of ddj_ckb.ckname
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public String getCkname() {
		return ckname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.ckname
	 * @param ckname  the value for ddj_ckb.ckname
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setCkname(String ckname) {
		this.ckname = ckname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.ckaddress
	 * @return  the value of ddj_ckb.ckaddress
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public String getCkaddress() {
		return ckaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.ckaddress
	 * @param ckaddress  the value for ddj_ckb.ckaddress
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setCkaddress(String ckaddress) {
		this.ckaddress = ckaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.cklxrid
	 * @return  the value of ddj_ckb.cklxrid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public Long getCklxrid() {
		return cklxrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.cklxrid
	 * @param cklxrid  the value for ddj_ckb.cklxrid
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setCklxrid(Long cklxrid) {
		this.cklxrid = cklxrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.cktype
	 * @return  the value of ddj_ckb.cktype
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public Integer getCktype() {
		return cktype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.cktype
	 * @param cktype  the value for ddj_ckb.cktype
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setCktype(Integer cktype) {
		this.cktype = cktype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.ckqhdz
	 * @return  the value of ddj_ckb.ckqhdz
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public String getCkqhdz() {
		return ckqhdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.ckqhdz
	 * @param ckqhdz  the value for ddj_ckb.ckqhdz
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setCkqhdz(String ckqhdz) {
		this.ckqhdz = ckqhdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.ckshdz
	 * @return  the value of ddj_ckb.ckshdz
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public String getCkshdz() {
		return ckshdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.ckshdz
	 * @param ckshdz  the value for ddj_ckb.ckshdz
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setCkshdz(String ckshdz) {
		this.ckshdz = ckshdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.status
	 * @return  the value of ddj_ckb.status
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.status
	 * @param status  the value for ddj_ckb.status
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	public void setStatus(Short status) {
		this.status = status;
	}
}