package com.jdy.ddj.entity;

public class DdjCkbKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.ckid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long ckid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_ckb.userid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.ckid
	 * @return  the value of ddj_ckb.ckid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getCkid() {
		return ckid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.ckid
	 * @param ckid  the value for ddj_ckb.ckid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setCkid(Long ckid) {
		this.ckid = ckid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_ckb.userid
	 * @return  the value of ddj_ckb.userid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_ckb.userid
	 * @param userid  the value for ddj_ckb.userid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}
}