package com.jdy.ddj.entity;

import java.util.Date;

public class DdjChat {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_chat.ltbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long ltbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_chat.khbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long khbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_chat.cjbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long cjbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_chat.ltnr
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String ltnr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_chat.ltsj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Date ltsj;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_chat.ltbh
	 * @return  the value of ddj_chat.ltbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getLtbh() {
		return ltbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_chat.ltbh
	 * @param ltbh  the value for ddj_chat.ltbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setLtbh(Long ltbh) {
		this.ltbh = ltbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_chat.khbh
	 * @return  the value of ddj_chat.khbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getKhbh() {
		return khbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_chat.khbh
	 * @param khbh  the value for ddj_chat.khbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setKhbh(Long khbh) {
		this.khbh = khbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_chat.cjbh
	 * @return  the value of ddj_chat.cjbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getCjbh() {
		return cjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_chat.cjbh
	 * @param cjbh  the value for ddj_chat.cjbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setCjbh(Long cjbh) {
		this.cjbh = cjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_chat.ltnr
	 * @return  the value of ddj_chat.ltnr
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getLtnr() {
		return ltnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_chat.ltnr
	 * @param ltnr  the value for ddj_chat.ltnr
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setLtnr(String ltnr) {
		this.ltnr = ltnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_chat.ltsj
	 * @return  the value of ddj_chat.ltsj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Date getLtsj() {
		return ltsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_chat.ltsj
	 * @param ltsj  the value for ddj_chat.ltsj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setLtsj(Date ltsj) {
		this.ltsj = ltsj;
	}
}