package com.jdy.ddj.entity;

import java.util.Date;

public class DdjJgdJchxq {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_jchxq.id
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_jchxq.gdid
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	private String gdid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_jchxq.userid
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_jchxq.usertype
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	private Short usertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_jchxq.jchdetail
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	private String jchdetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_jchxq.quantity
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	private Double quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_jchxq.qrtime
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	private Date qrtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_jchxq.id
	 * @return  the value of ddj_jgd_jchxq.id
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_jchxq.id
	 * @param id  the value for ddj_jgd_jchxq.id
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_jchxq.gdid
	 * @return  the value of ddj_jgd_jchxq.gdid
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public String getGdid() {
		return gdid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_jchxq.gdid
	 * @param gdid  the value for ddj_jgd_jchxq.gdid
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public void setGdid(String gdid) {
		this.gdid = gdid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_jchxq.userid
	 * @return  the value of ddj_jgd_jchxq.userid
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_jchxq.userid
	 * @param userid  the value for ddj_jgd_jchxq.userid
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_jchxq.usertype
	 * @return  the value of ddj_jgd_jchxq.usertype
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public Short getUsertype() {
		return usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_jchxq.usertype
	 * @param usertype  the value for ddj_jgd_jchxq.usertype
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public void setUsertype(Short usertype) {
		this.usertype = usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_jchxq.jchdetail
	 * @return  the value of ddj_jgd_jchxq.jchdetail
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public String getJchdetail() {
		return jchdetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_jchxq.jchdetail
	 * @param jchdetail  the value for ddj_jgd_jchxq.jchdetail
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public void setJchdetail(String jchdetail) {
		this.jchdetail = jchdetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_jchxq.quantity
	 * @return  the value of ddj_jgd_jchxq.quantity
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public Double getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_jchxq.quantity
	 * @param quantity  the value for ddj_jgd_jchxq.quantity
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_jchxq.qrtime
	 * @return  the value of ddj_jgd_jchxq.qrtime
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public Date getQrtime() {
		return qrtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_jchxq.qrtime
	 * @param qrtime  the value for ddj_jgd_jchxq.qrtime
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	public void setQrtime(Date qrtime) {
		this.qrtime = qrtime;
	}
}