package com.jdy.ddj.entity;

import java.util.Date;

public class DdjJgd {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.gdid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private String gdid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.khid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private Long khid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.cjid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private Long cjid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.productname
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private String productname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.cpcz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private String cpcz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.dzlx
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private String dzlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.price
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.quantitytype
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private Integer quantitytype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.quantity
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private String quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.totalprice
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private Double totalprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.photos
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private String photos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.khqhdz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private String khqhdz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.khshdz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private String khshdz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.status
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd.cssj
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	private Date cssj;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.gdid
	 * @return  the value of ddj_jgd.gdid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public String getGdid() {
		return gdid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.gdid
	 * @param gdid  the value for ddj_jgd.gdid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setGdid(String gdid) {
		this.gdid = gdid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.khid
	 * @return  the value of ddj_jgd.khid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public Long getKhid() {
		return khid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.khid
	 * @param khid  the value for ddj_jgd.khid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setKhid(Long khid) {
		this.khid = khid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.cjid
	 * @return  the value of ddj_jgd.cjid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public Long getCjid() {
		return cjid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.cjid
	 * @param cjid  the value for ddj_jgd.cjid
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setCjid(Long cjid) {
		this.cjid = cjid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.productname
	 * @return  the value of ddj_jgd.productname
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public String getProductname() {
		return productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.productname
	 * @param productname  the value for ddj_jgd.productname
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setProductname(String productname) {
		this.productname = productname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.cpcz
	 * @return  the value of ddj_jgd.cpcz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public String getCpcz() {
		return cpcz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.cpcz
	 * @param cpcz  the value for ddj_jgd.cpcz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setCpcz(String cpcz) {
		this.cpcz = cpcz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.dzlx
	 * @return  the value of ddj_jgd.dzlx
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public String getDzlx() {
		return dzlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.dzlx
	 * @param dzlx  the value for ddj_jgd.dzlx
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setDzlx(String dzlx) {
		this.dzlx = dzlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.price
	 * @return  the value of ddj_jgd.price
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.price
	 * @param price  the value for ddj_jgd.price
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.quantitytype
	 * @return  the value of ddj_jgd.quantitytype
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public Integer getQuantitytype() {
		return quantitytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.quantitytype
	 * @param quantitytype  the value for ddj_jgd.quantitytype
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setQuantitytype(Integer quantitytype) {
		this.quantitytype = quantitytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.quantity
	 * @return  the value of ddj_jgd.quantity
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public String getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.quantity
	 * @param quantity  the value for ddj_jgd.quantity
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.totalprice
	 * @return  the value of ddj_jgd.totalprice
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public Double getTotalprice() {
		return totalprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.totalprice
	 * @param totalprice  the value for ddj_jgd.totalprice
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setTotalprice(Double totalprice) {
		this.totalprice = totalprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.photos
	 * @return  the value of ddj_jgd.photos
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public String getPhotos() {
		return photos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.photos
	 * @param photos  the value for ddj_jgd.photos
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setPhotos(String photos) {
		this.photos = photos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.khqhdz
	 * @return  the value of ddj_jgd.khqhdz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public String getKhqhdz() {
		return khqhdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.khqhdz
	 * @param khqhdz  the value for ddj_jgd.khqhdz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setKhqhdz(String khqhdz) {
		this.khqhdz = khqhdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.khshdz
	 * @return  the value of ddj_jgd.khshdz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public String getKhshdz() {
		return khshdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.khshdz
	 * @param khshdz  the value for ddj_jgd.khshdz
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setKhshdz(String khshdz) {
		this.khshdz = khshdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.status
	 * @return  the value of ddj_jgd.status
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.status
	 * @param status  the value for ddj_jgd.status
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd.cssj
	 * @return  the value of ddj_jgd.cssj
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public Date getCssj() {
		return cssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd.cssj
	 * @param cssj  the value for ddj_jgd.cssj
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	public void setCssj(Date cssj) {
		this.cssj = cssj;
	}
}