package com.jdy.ddj.entity;

public class DdjJgdResKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_res.gdbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String gdbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_res.resid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long resid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_res.gdbh
	 * @return  the value of ddj_jgd_res.gdbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getGdbh() {
		return gdbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_res.gdbh
	 * @param gdbh  the value for ddj_jgd_res.gdbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setGdbh(String gdbh) {
		this.gdbh = gdbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_res.resid
	 * @return  the value of ddj_jgd_res.resid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getResid() {
		return resid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_res.resid
	 * @param resid  the value for ddj_jgd_res.resid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setResid(Long resid) {
		this.resid = resid;
	}
}