package com.jdy.ddj.entity;

public class DdjJgdRes extends DdjJgdResKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_res.picname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String picname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_res.respic
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String respic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_jgd_res.sortid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long sortid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_res.picname
	 * @return  the value of ddj_jgd_res.picname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getPicname() {
		return picname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_res.picname
	 * @param picname  the value for ddj_jgd_res.picname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setPicname(String picname) {
		this.picname = picname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_res.respic
	 * @return  the value of ddj_jgd_res.respic
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getRespic() {
		return respic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_res.respic
	 * @param respic  the value for ddj_jgd_res.respic
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setRespic(String respic) {
		this.respic = respic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_jgd_res.sortid
	 * @return  the value of ddj_jgd_res.sortid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getSortid() {
		return sortid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_jgd_res.sortid
	 * @param sortid  the value for ddj_jgd_res.sortid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setSortid(Long sortid) {
		this.sortid = sortid;
	}
}