package com.jdy.ddj.entity;

import java.util.Date;

public class DdjKhCj extends DdjKhCjKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_kh_cj.gltime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Date gltime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_kh_cj.gltime
	 * @return  the value of ddj_kh_cj.gltime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Date getGltime() {
		return gltime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_kh_cj.gltime
	 * @param gltime  the value for ddj_kh_cj.gltime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setGltime(Date gltime) {
		this.gltime = gltime;
	}
}