package com.jdy.ddj.entity;

public class DdjKhCjKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_kh_cj.userid_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long useridCj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_kh_cj.userid_kh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long useridKh;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_kh_cj.userid_cj
	 * @return  the value of ddj_kh_cj.userid_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getUseridCj() {
		return useridCj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_kh_cj.userid_cj
	 * @param useridCj  the value for ddj_kh_cj.userid_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setUseridCj(Long useridCj) {
		this.useridCj = useridCj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_kh_cj.userid_kh
	 * @return  the value of ddj_kh_cj.userid_kh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getUseridKh() {
		return useridKh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_kh_cj.userid_kh
	 * @param useridKh  the value for ddj_kh_cj.userid_kh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setUseridKh(Long useridKh) {
		this.useridKh = useridKh;
	}
}