package com.jdy.ddj.entity;

import java.util.Date;

public class DdjPfb extends DdjPfbKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_pfb.pftime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Date pftime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_pfb.score
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Integer score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_pfb.pftime
	 * @return  the value of ddj_pfb.pftime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Date getPftime() {
		return pftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_pfb.pftime
	 * @param pftime  the value for ddj_pfb.pftime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setPftime(Date pftime) {
		this.pftime = pftime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_pfb.score
	 * @return  the value of ddj_pfb.score
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_pfb.score
	 * @param score  the value for ddj_pfb.score
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setScore(Integer score) {
		this.score = score;
	}
}