package com.jdy.ddj.entity;

public class DdjPfbKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_pfb.userid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_pfb.userid_kh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long useridKh;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_pfb.userid
	 * @return  the value of ddj_pfb.userid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_pfb.userid
	 * @param userid  the value for ddj_pfb.userid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_pfb.userid_kh
	 * @return  the value of ddj_pfb.userid_kh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getUseridKh() {
		return useridKh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_pfb.userid_kh
	 * @param useridKh  the value for ddj_pfb.userid_kh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setUseridKh(Long useridKh) {
		this.useridKh = useridKh;
	}
}