package com.jdy.ddj.entity;

import java.util.Date;

public class DdjRes {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_res.resid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long resid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_res.picname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String picname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_res.picurl
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private String picurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_res.uploadtime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Date uploadtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_res.resid
	 * @return  the value of ddj_res.resid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getResid() {
		return resid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_res.resid
	 * @param resid  the value for ddj_res.resid
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setResid(Long resid) {
		this.resid = resid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_res.picname
	 * @return  the value of ddj_res.picname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getPicname() {
		return picname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_res.picname
	 * @param picname  the value for ddj_res.picname
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setPicname(String picname) {
		this.picname = picname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_res.picurl
	 * @return  the value of ddj_res.picurl
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public String getPicurl() {
		return picurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_res.picurl
	 * @param picurl  the value for ddj_res.picurl
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setPicurl(String picurl) {
		this.picurl = picurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_res.uploadtime
	 * @return  the value of ddj_res.uploadtime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Date getUploadtime() {
		return uploadtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_res.uploadtime
	 * @param uploadtime  the value for ddj_res.uploadtime
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setUploadtime(Date uploadtime) {
		this.uploadtime = uploadtime;
	}
}