package com.jdy.ddj.entity;

import java.util.Date;

public class DdjSjKhck extends DdjSjKhckKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_sj_khck.glsj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Date glsj;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_sj_khck.glsj
	 * @return  the value of ddj_sj_khck.glsj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Date getGlsj() {
		return glsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_sj_khck.glsj
	 * @param glsj  the value for ddj_sj_khck.glsj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setGlsj(Date glsj) {
		this.glsj = glsj;
	}
}