package com.jdy.ddj.entity;

public class DdjSjKhckKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_sj_khck.ckbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long ckbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_sj_khck.sjbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	private Long sjbh;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_sj_khck.ckbh
	 * @return  the value of ddj_sj_khck.ckbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getCkbh() {
		return ckbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_sj_khck.ckbh
	 * @param ckbh  the value for ddj_sj_khck.ckbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setCkbh(Long ckbh) {
		this.ckbh = ckbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_sj_khck.sjbh
	 * @return  the value of ddj_sj_khck.sjbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public Long getSjbh() {
		return sjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_sj_khck.sjbh
	 * @param sjbh  the value for ddj_sj_khck.sjbh
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	public void setSjbh(Long sjbh) {
		this.sjbh = sjbh;
	}
}