package com.jdy.ddj.entity;

public class DdjUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.userid
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.username
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.telephone
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.password
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.status
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.idcard
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.zcnumber
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private String zcnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.usertype
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private Short usertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.companyid
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private Long companyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.sfzzmpic
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private String sfzzmpic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.sfzfmpic
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private String sfzfmpic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.licence
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private String licence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_user.audit
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	private Short audit;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.userid
	 * @return  the value of ddj_user.userid
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.userid
	 * @param userid  the value for ddj_user.userid
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.username
	 * @return  the value of ddj_user.username
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.username
	 * @param username  the value for ddj_user.username
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.telephone
	 * @return  the value of ddj_user.telephone
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.telephone
	 * @param telephone  the value for ddj_user.telephone
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.password
	 * @return  the value of ddj_user.password
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.password
	 * @param password  the value for ddj_user.password
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.status
	 * @return  the value of ddj_user.status
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.status
	 * @param status  the value for ddj_user.status
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.idcard
	 * @return  the value of ddj_user.idcard
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.idcard
	 * @param idcard  the value for ddj_user.idcard
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.zcnumber
	 * @return  the value of ddj_user.zcnumber
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public String getZcnumber() {
		return zcnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.zcnumber
	 * @param zcnumber  the value for ddj_user.zcnumber
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setZcnumber(String zcnumber) {
		this.zcnumber = zcnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.usertype
	 * @return  the value of ddj_user.usertype
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public Short getUsertype() {
		return usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.usertype
	 * @param usertype  the value for ddj_user.usertype
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setUsertype(Short usertype) {
		this.usertype = usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.companyid
	 * @return  the value of ddj_user.companyid
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public Long getCompanyid() {
		return companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.companyid
	 * @param companyid  the value for ddj_user.companyid
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setCompanyid(Long companyid) {
		this.companyid = companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.sfzzmpic
	 * @return  the value of ddj_user.sfzzmpic
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public String getSfzzmpic() {
		return sfzzmpic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.sfzzmpic
	 * @param sfzzmpic  the value for ddj_user.sfzzmpic
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setSfzzmpic(String sfzzmpic) {
		this.sfzzmpic = sfzzmpic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.sfzfmpic
	 * @return  the value of ddj_user.sfzfmpic
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public String getSfzfmpic() {
		return sfzfmpic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.sfzfmpic
	 * @param sfzfmpic  the value for ddj_user.sfzfmpic
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setSfzfmpic(String sfzfmpic) {
		this.sfzfmpic = sfzfmpic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.licence
	 * @return  the value of ddj_user.licence
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public String getLicence() {
		return licence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.licence
	 * @param licence  the value for ddj_user.licence
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setLicence(String licence) {
		this.licence = licence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_user.audit
	 * @return  the value of ddj_user.audit
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public Short getAudit() {
		return audit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_user.audit
	 * @param audit  the value for ddj_user.audit
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	public void setAudit(Short audit) {
		this.audit = audit;
	}
}