package com.jdy.ddj.entity;

import java.util.Date;

public class DdjZdb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_zdb.id
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_zdb.khbh
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	private Long khbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_zdb.cjbh
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	private Long cjbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_zdb.paytype
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	private String paytype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_zdb.payprice
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	private Double payprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_zdb.status
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ddj_zdb.createtime
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	private Date createtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_zdb.id
	 * @return  the value of ddj_zdb.id
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_zdb.id
	 * @param id  the value for ddj_zdb.id
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_zdb.khbh
	 * @return  the value of ddj_zdb.khbh
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public Long getKhbh() {
		return khbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_zdb.khbh
	 * @param khbh  the value for ddj_zdb.khbh
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public void setKhbh(Long khbh) {
		this.khbh = khbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_zdb.cjbh
	 * @return  the value of ddj_zdb.cjbh
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public Long getCjbh() {
		return cjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_zdb.cjbh
	 * @param cjbh  the value for ddj_zdb.cjbh
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public void setCjbh(Long cjbh) {
		this.cjbh = cjbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_zdb.paytype
	 * @return  the value of ddj_zdb.paytype
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public String getPaytype() {
		return paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_zdb.paytype
	 * @param paytype  the value for ddj_zdb.paytype
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public void setPaytype(String paytype) {
		this.paytype = paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_zdb.payprice
	 * @return  the value of ddj_zdb.payprice
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public Double getPayprice() {
		return payprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_zdb.payprice
	 * @param payprice  the value for ddj_zdb.payprice
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public void setPayprice(Double payprice) {
		this.payprice = payprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_zdb.status
	 * @return  the value of ddj_zdb.status
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_zdb.status
	 * @param status  the value for ddj_zdb.status
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ddj_zdb.createtime
	 * @return  the value of ddj_zdb.createtime
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ddj_zdb.createtime
	 * @param createtime  the value for ddj_zdb.createtime
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
}