package com.jdy.ddj.dao;

import com.jdy.ddj.entity.DdjArea;

public interface DdjAreaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_area
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int deleteByPrimaryKey(String areaid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_area
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insert(DdjArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_area
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insertSelective(DdjArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_area
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	DdjArea selectByPrimaryKey(String areaid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_area
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_area
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKey(DdjArea record);
}