package com.jdy.ddj.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jdy.ddj.common.dao.RequestBean;
import com.jdy.ddj.entity.DdjBjd;

public interface DdjBjdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_bjd
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	int deleteByPrimaryKey(Long ywid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_bjd
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	int insert(DdjBjd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_bjd
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	int insertSelective(DdjBjd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_bjd
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	DdjBjd selectByPrimaryKey(Long ywid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_bjd
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjBjd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_bjd
	 * @mbggenerated  Thu Nov 26 09:07:13 CST 2015
	 */
	int updateByPrimaryKey(DdjBjd record);

	long count(@Param("requestBean")RequestBean requestBean);

	List<DdjBjd> findPage(@Param("requestBean")RequestBean requestBean);
	
	
	
}