package com.jdy.ddj.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jdy.ddj.common.dao.RequestBean;
import com.jdy.ddj.entity.DdjCkb;

public interface DdjCkbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_ckb
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	int deleteByPrimaryKey(Long ckid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_ckb
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	int insert(DdjCkb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_ckb
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	int insertSelective(DdjCkb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_ckb
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	DdjCkb selectByPrimaryKey(Long ckid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_ckb
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjCkb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_ckb
	 * @mbggenerated  Sat Dec 12 14:24:15 CST 2015
	 */
	int updateByPrimaryKey(DdjCkb record);

	long count(@Param("requestBean")RequestBean requestBean);

	List<DdjCkb> findPage(@Param("requestBean")RequestBean requestBean);
	
	
    /**
     * @param record 
	 * 根据不为空的字段查询
     */
    List<DdjCkb> getByValues(DdjCkb record);
}