package com.jdy.ddj.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jdy.ddj.common.dao.RequestBean;
import com.jdy.ddj.entity.DdjCompany;

public interface DdjCompanyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_company
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int deleteByPrimaryKey(Long companyid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_company
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insert(DdjCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_company
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insertSelective(DdjCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_company
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	DdjCompany selectByPrimaryKey(Long companyid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_company
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjCompany record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_company
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKey(DdjCompany record);
	
    /**
     * @param ddjCompany 
	 * 根据不为空的字段查询
     */
    List<DdjCompany> getByValues(DdjCompany ddjCompany);
    
    
    /**
     * @param requestBean 
	 * 查询总数
     */
    long count(@Param("requestBean") RequestBean requestBean);
    
    /**
     * @param requestBean 
	 * 分页查询
     */
    List<DdjCompany> findPage(@Param("requestBean") RequestBean requestBean);

    
    void updateValuesById(DdjCompany ddjCompany);
    
    
    List<DdjCompany> getJgdCjList(long useridKh);
    List<DdjCompany> getJgdKhList(long useridCj);
}