package com.jdy.ddj.dao;

import com.jdy.ddj.entity.DdjChat;

public interface DdjChatMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_chat
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int deleteByPrimaryKey(Long ltbh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_chat
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insert(DdjChat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_chat
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insertSelective(DdjChat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_chat
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	DdjChat selectByPrimaryKey(Long ltbh);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_chat
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjChat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_chat
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKey(DdjChat record);
}