package com.jdy.ddj.dao;

import java.util.List;

import com.jdy.ddj.entity.DdjJgdJchxq;

public interface DdjJgdJchxqMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_jchxq
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_jchxq
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	int insert(DdjJgdJchxq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_jchxq
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	int insertSelective(DdjJgdJchxq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_jchxq
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	DdjJgdJchxq selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_jchxq
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjJgdJchxq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_jchxq
	 * @mbggenerated  Thu Dec 10 14:47:21 CST 2015
	 */
	int updateByPrimaryKey(DdjJgdJchxq record);

	List<DdjJgdJchxq> getByValues(DdjJgdJchxq record);
}