package com.jdy.ddj.dao;

import com.jdy.ddj.entity.DdjJgdRes;
import com.jdy.ddj.entity.DdjJgdResKey;

public interface DdjJgdResMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int deleteByPrimaryKey(DdjJgdResKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insert(DdjJgdRes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insertSelective(DdjJgdRes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	DdjJgdRes selectByPrimaryKey(DdjJgdResKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjJgdRes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKey(DdjJgdRes record);
}