package com.jdy.ddj.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.jdy.ddj.common.dao.RequestBean;
import com.jdy.ddj.entity.DdjJgd;

public interface DdjJgdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	int deleteByPrimaryKey(String gdid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	int insert(DdjJgd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	int insertSelective(DdjJgd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	DdjJgd selectByPrimaryKey(String gdid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjJgd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_jgd
	 * @mbggenerated  Mon Nov 23 20:46:04 CST 2015
	 */
	int updateByPrimaryKey(DdjJgd record);

	long count(@Param("requestBean")RequestBean requestBean);

	List<DdjJgd> findPage(@Param("requestBean")RequestBean requestBean);

	List<DdjJgd> getByValues(DdjJgd ddjjgd);
	
	List<Map> getTotalStat(DdjJgd ddjjgd);
	
}