package com.jdy.ddj.dao;

import java.util.List;

import com.jdy.ddj.entity.DdjKhCj;
import com.jdy.ddj.entity.DdjKhCjKey;

public interface DdjKhCjMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_kh_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int deleteByPrimaryKey(DdjKhCjKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_kh_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insert(DdjKhCj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_kh_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insertSelective(DdjKhCj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_kh_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	DdjKhCj selectByPrimaryKey(DdjKhCjKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_kh_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjKhCj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_kh_cj
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKey(DdjKhCj record);
	
	/**
     * @param ddjkhcj 
	 * 根据不为空的字段查询
     */
    List<DdjKhCj> getByValues(DdjKhCj ddjkhcj);
    
    
    List<String> getCompnayIdByValues(DdjKhCj ddjkhcj);
}