package com.jdy.ddj.dao;

import com.jdy.ddj.entity.DdjPfb;
import com.jdy.ddj.entity.DdjPfbKey;

public interface DdjPfbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_pfb
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int deleteByPrimaryKey(DdjPfbKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_pfb
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insert(DdjPfb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_pfb
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insertSelective(DdjPfb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_pfb
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	DdjPfb selectByPrimaryKey(DdjPfbKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_pfb
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjPfb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_pfb
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKey(DdjPfb record);
}