package com.jdy.ddj.dao;

import com.jdy.ddj.entity.DdjRes;

public interface DdjResMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int deleteByPrimaryKey(Long resid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insert(DdjRes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insertSelective(DdjRes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	DdjRes selectByPrimaryKey(Long resid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjRes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_res
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKey(DdjRes record);
}