package com.jdy.ddj.dao;

import java.util.List;

import com.jdy.ddj.entity.DdjSjKhck;
import com.jdy.ddj.entity.DdjSjKhckKey;

public interface DdjSjKhckMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_sj_khck
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int deleteByPrimaryKey(DdjSjKhckKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_sj_khck
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insert(DdjSjKhck record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_sj_khck
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int insertSelective(DdjSjKhck record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_sj_khck
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	DdjSjKhck selectByPrimaryKey(DdjSjKhckKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_sj_khck
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjSjKhck record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_sj_khck
	 * @mbggenerated  Tue Nov 17 16:36:05 CST 2015
	 */
	int updateByPrimaryKey(DdjSjKhck record);
	
	List<DdjSjKhck> getByValues(DdjSjKhck record);
}