package com.jdy.ddj.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jdy.ddj.common.dao.RequestBean;
import com.jdy.ddj.entity.DdjUser;

public interface DdjUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_user
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	int deleteByPrimaryKey(Long userid);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_user
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	int insert(DdjUser record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_user
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	int insertSelective(DdjUser record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_user
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	DdjUser selectByPrimaryKey(Long userid);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_user
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	int updateByPrimaryKeySelective(DdjUser record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_user
	 * @mbggenerated  Sat Dec 12 14:19:53 CST 2015
	 */
	int updateByPrimaryKey(DdjUser record);


	/**
     * @param ddjUser 
	 * 根据不为空的字段查询
     */
    List<DdjUser> getByValues(DdjUser ddjUser);
    
    
    List<DdjUser> getByIds(String ids);
    
    long count(@Param("requestBean")RequestBean requestBean);

	List<DdjUser> findPage(@Param("requestBean")RequestBean requestBean);
    
}