package com.jdy.ddj.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jdy.ddj.common.dao.RequestBean;
import com.jdy.ddj.entity.DdjZdb;

public interface DdjZdbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_zdb
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_zdb
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	int insert(DdjZdb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_zdb
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	int insertSelective(DdjZdb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_zdb
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	DdjZdb selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_zdb
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	int updateByPrimaryKeySelective(DdjZdb record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ddj_zdb
	 * @mbggenerated  Sun Jan 17 17:30:38 CST 2016
	 */
	int updateByPrimaryKey(DdjZdb record);
	
	 List<DdjZdb> getByValues(DdjZdb record);

	long count(@Param("requestBean")RequestBean requestBean);

	List<DdjZdb> findPage(@Param("requestBean")RequestBean requestBean);
}